#!/usr/bin/env node
/**
 * 生成 /test/ 测试版（GitHub Pages 没有构建步骤，所以生成结果直接提交）。
 *   node tools/build-test.js          # 从根目录文件重新生成 test/
 *   node tools/build-test.js --check  # 只校验 test/ 与生成结果一致（npm test 里也会校验）
 *
 * 正式版（根目录）与测试版是同一份代码、同一个版本号，只差：
 *   1. game.js 的 FEATURES.EVAL_ALLOWED  false → true（评测 / 数据 / 评测面板 / ?eval=1 只在测试版存在）
 *   2. game.js 的 FEATURES.BUILD_ENV     "public" → "test"（埋点：build 带 -test 后缀，econ="test"，另带 env:"test"，统计查询自然排除）
 *   3. 所有 localStorage / sessionStorage 键加前缀 test_（同一个域名 gosuquan.github.io 下，测试版存档不会和正式版互串）
 *   4. 页面标题加「[测试版]」+ 右下角小标签 + noindex
 * 不要手改 test/ 下的文件——改根目录文件，然后重新运行本脚本。
 */
"use strict";
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const OUT = path.join(ROOT, "test");
const FILES = ["index.html", "game.js", "style.css", "audio.js", "platform.js", "version.json"];
const KEY_PREFIX = "test_";
const BANNER_CSS = `
/* test build only (tools/build-test.js) */
.test-build-tag { position: fixed; right: 0; bottom: 0; z-index: 99999; padding: 2px 8px; font: 600 11px/1.4 system-ui, sans-serif;
  color: #1b1200; background: #ffb020; border-top-left-radius: 6px; opacity: .92; pointer-events: none; }
`;

function replaceOnce(src, from, to, label) {
  const n = src.split(from).length - 1;
  if (n !== 1) throw new Error(`build-test: expected exactly 1 "${label || from}" in source, found ${n}`);
  return src.replace(from, to);
}
/** every storage key literal in the game starts with deltaStash / auctionHelpSeen */
function prefixKeys(src, file) {
  let count = 0;
  const out = src
    .replace(/(["'`])(deltaStash[A-Za-z0-9_]*)\1/g, (_m, q, k) => { count++; return `${q}${KEY_PREFIX}${k}${q}`; })
    .replace(/(["'`])(auctionHelpSeen)\1/g, (_m, q, k) => { count++; return `${q}${KEY_PREFIX}${k}${q}`; });
  return { out, count };
}

function build() {
  const out = {};
  for (const f of FILES) {
    let s = fs.readFileSync(path.join(ROOT, f), "utf8");
    if (f === "game.js") {
      s = replaceOnce(s, "EVAL_ALLOWED: false,", "EVAL_ALLOWED: true,", "EVAL_ALLOWED: false,");
      s = replaceOnce(s, 'BUILD_ENV: "public",', 'BUILD_ENV: "test",', 'BUILD_ENV: "public",');
    }
    if (f.endsWith(".js")) {
      const { out: o, count } = prefixKeys(s, f);
      s = o;
      if (f === "game.js" && count < 10) throw new Error(`build-test: only ${count} storage keys prefixed in game.js — pattern broke?`);
      if (f === "audio.js" && count < 1) throw new Error("build-test: audio.js storage key not prefixed");
      s = `/* AUTO-GENERATED by tools/build-test.js from the root ${f} — do not edit; run \`node tools/build-test.js\`. */\n` + s;
    }
    if (f === "index.html") {
      s = replaceOnce(s, "<title>", "<title>[测试版] ", "<title>");
      s = replaceOnce(s, "</head>", '  <meta name="robots" content="noindex" />\n</head>', "</head>");
      s = replaceOnce(s, /<body[^>]*>/.exec(s)[0], (/<body[^>]*>/.exec(s)[0]) + '\n  <div class="test-build-tag" aria-hidden="true">测试版 · 存档独立</div>', "<body>");
      s = s.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n<!-- AUTO-GENERATED by tools/build-test.js from the root index.html — do not edit. -->");
    }
    if (f === "style.css") {
      s = `/* AUTO-GENERATED by tools/build-test.js from the root style.css — do not edit. */\n` + s + BANNER_CSS;
    }
    out[f] = s;
  }
  return out;
}

/** → list of problems ([] = test/ matches the generator output exactly) */
function check() {
  const want = build();
  const problems = [];
  for (const [f, s] of Object.entries(want)) {
    let have = null;
    try { have = fs.readFileSync(path.join(OUT, f), "utf8"); } catch (_) { /* missing */ }
    if (have === null) problems.push(`test/${f} missing`);
    else if (have !== s) problems.push(`test/${f} is out of date`);
  }
  let extra = [];
  try { extra = fs.readdirSync(OUT).filter((f) => !(f in want)); } catch (_) { /* no dir */ }
  for (const f of extra) problems.push(`test/${f} is not generated (stray file)`);
  return problems;
}

function write() {
  const files = build();
  fs.mkdirSync(OUT, { recursive: true });
  for (const f of fs.readdirSync(OUT)) if (!(f in files)) fs.rmSync(path.join(OUT, f), { recursive: true, force: true });
  for (const [f, s] of Object.entries(files)) fs.writeFileSync(path.join(OUT, f), s);
  return Object.keys(files);
}

module.exports = { build, check, write, FILES, KEY_PREFIX };

if (require.main === module) {
  if (process.argv.includes("--check")) {
    const p = check();
    if (p.length) { console.error("test/ out of sync:\n  " + p.join("\n  ") + "\n→ run: node tools/build-test.js"); process.exit(1); }
    console.log("test/ is in sync with the generator");
  } else {
    const fl = write();
    const ver = JSON.parse(fs.readFileSync(path.join(OUT, "version.json"), "utf8")).version;
    console.log(`test/ regenerated (${fl.join(", ")}) · version ${ver}`);
  }
}
